// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesWebApi.DbContexts;

namespace MoviesWebApi.Migrations
{
    [DbContext(typeof(PeliculasDbContext))]
    [Migration("20220124045814_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MoviesWebApi.Models.Genero", b =>
                {
                    b.Property<int>("id_genero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_genero");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("MoviesWebApi.Models.Pelicula", b =>
                {
                    b.Property<int>("id_pelicula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Generoid_genero")
                        .HasColumnType("int");

                    b.Property<int>("anio_publicacion")
                        .HasColumnType("int");

                    b.Property<string>("director")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_genero")
                        .HasColumnType("int");

                    b.Property<int>("puntuacion")
                        .HasColumnType("int");

                    b.Property<int>("rating")
                        .HasColumnType("int");

                    b.Property<string>("titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_pelicula");

                    b.HasIndex("Generoid_genero");

                    b.ToTable("Peliculas");
                });

            modelBuilder.Entity("MoviesWebApi.Models.Pelicula", b =>
                {
                    b.HasOne("MoviesWebApi.Models.Genero", "Genero")
                        .WithMany("Peliculas")
                        .HasForeignKey("Generoid_genero");

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("MoviesWebApi.Models.Genero", b =>
                {
                    b.Navigation("Peliculas");
                });
#pragma warning restore 612, 618
        }
    }
}
